### ISSUE TITLE
Error [63]: Memory error

### ISSUE THREAD

**Issue by copa-light** [semiautomaticgit/SemiAutomaticClassificationPlugin#193] opened 2021-11-02 07:22 UTC
Hello!
I'm using SCP for unsupervised classification and accracy assessment.
But when I try to accuracy assessment from classified Landsat image, I have the Error [63] ('Memory error, too many combinations. Try to reclassify the values').
I already reclassified image into 5 classes, and changed available RAM into 16 GB. (RAM of my computer is 32 GB)
Reference file has 'id' and 'class' for original data.

This is the error log of my processing.

![image](https://user-images.githubusercontent.com/93574347/139802760-9352f738-bd0d-48b6-91c0-7d725874a971.png)

[error.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/7458531/error.txt)

Is it related with failed SNAP subprocess? Or how can I solve it?

Thank you :)

**Comment by semiautomaticgit** [comment] 2021-11-03 17:32
Hello @copa-light ,
the issue is not related to SNAP.
Possibly it is related to input data.
Are you using vector as reference data?
Also, please check if there are NoData values in the classification raster.

**Comment by semiautomaticgit** [comment] 2022-09-07 21:46
I'm closing this, but of course reopen this if you still have issues.

**Closed by semiautomaticgit** 2022-09-07 21:46 UTC
