### ISSUE TITLE
SCP 7.2.0 - sentinel2Tab-sentinelReflectance 337 ERROR exception: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#145] opened 2020-12-06 00:08 UTC
Dear @semiautomaticgit 

After upgrade SCP to 7.2.0, I'm getting this error:

```
2020-12-05 23.46.35.772769	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-sentinelReflectance 337	 ERROR exception: 'NoneType' object is not subscriptable
2020-12-05 23.46.35.826624	SemiAutomaticClassificationPlugin.maininterface.sentinel2Tab-sentinel2 287	WARNING: unable to load raster
```

Here is the complete log file:
[Error_SCP_7.2.0.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5648054/Error_SCP_7.2.0.txt)

I'm repeating a workflow that I've done dozens of times in last weeks. The steps are illustrated in images here: https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/130#issue-739877239

I've also tried it with SCP 7.1.1 that I still have on another user profile, and it works fine.

So it seems to be something introduced in 7.2.0.

Can you confirm?

Thanks Luca!

**Comment by semiautomaticgit** [comment] 2020-12-06 09:50
Dear @PedroVenancio ,

the Sentinel-2 tool should be the same in version 7.1.1 and 7.2.0.
I can't reproduce in QGIS 3.14. I think it is an issue related to the QGIS version. 
Possibly you tested it with the OSGEO installation of QGIS?

**Comment by semiautomaticgit** [comment] 2020-12-06 10:00
Thank you @PedroVenancio , I think I found the cause of the issue. I'll fix it

**Comment by PedroVenancio** [comment] 2020-12-06 13:36
Hi Luca,

Possibly some kind of side effect, but it happens in SCP 7.2.0 and not in 7.1.1, in same QGIS version (3.16.1).

Thank you very much Luca!

**Comment by semiautomaticgit** [comment] 2020-12-06 18:48
Hi @PedroVenancio , it should be fixed in version 7.2.1. 
Please update the plugin

**Closed by semiautomaticgit** 2020-12-06 18:48 UTC

**Comment by PedroVenancio** [comment] 2020-12-06 23:28
Fix confirmed @semiautomaticgit ! Thank you very much!!

**Comment by semiautomaticgit** [comment] 2020-12-07 00:03
Thank you for your feedback @PedroVenancio
