### ISSUE TITLE
Spectral Signature Plot does not correctly calculate the ROI values in each band

### ISSUE THREAD

**Issue by claudioasn** [semiautomaticgit/SemiAutomaticClassificationPlugin#312] opened 2023-11-06 15:10 UTC
I'm using SCP version 8.1.3, with remotior-sensus updated. When I generate the ROIs and calculate their spectral signature, when I display it on the plot it looks as if the value is the same in all the bands. Until version 7 this worked normally, but now it's giving me this problem. The scatterplot presents the same problem.

![scp_plot](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/104084558/bf6f70ae-9138-4802-af72-d33364f794cd)

![scp_details](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/104084558/11925419-eb0a-46aa-b9fb-18d198fcf3b5)

**Comment by semiautomaticgit** [comment] 2023-11-06 19:56
Hello, please update Remotior Sensus. 
If you still get the same issue, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by claudioasn** [comment] 2023-11-08 20:23
Hello, I already have the SCP and remotior-sensus updated, I had them before.

I tried to do the process, but QGIS doesn't exactly display an error message. I tried to do the whole process and save the .txt file, but it comes up blank.

What I did was open the landsat 8 bands, generate the DOS process, make a stack with the 7 optical bands, define the stack bands as bandset and create the ROIs for spectral plot.

It seems that SCP (or remotior-sensus) only captures the pixel value of one of the bands, and not all of the bands in the stack, or even all of the bandset, and the plot is not displayed correctly.

NOTE: I don't know if I need to open another topic, but I noticed another problem: with a bandset defined from a stack of bands (I tested with several scenes) there was a problem when making a PCA. The covariance matrix has the same value in all cells, the correlation matrix is empty, and the eigenvectors and eigenvalues also have problems. Before version 8 of SCP, which has the remotior-sensus dependency, I did exactly the same procedure and it worked normally.

Here is the PCA .txt file.

[PCA_N.csv](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/13301010/PCA_N.csv)

**Comment by semiautomaticgit** [comment] 2023-11-08 21:13
Hello @claudioasn ,


> What I did was open the landsat 8 bands, generate the DOS process, make a stack with the 7 optical bands, define the stack bands as bandset and create the ROIs for spectral plot.

stacking bands is not required as you can directly define the bandset using single bands. Could you please try without stacking bands?

**Comment by claudioasn** [comment] 2023-11-11 00:35
Hello @semiautomaticgit , when I used the separate bands the spectral plot worked for the rois. However, when I generate a stack of bands and load it as a bandset, this problem occurs. It's as if it captured the value of only one of the bands and not all seven, showing the same value for all of them.

Could the problem be in the construction of the stack and/or when it is loaded into the bandset? I've tried saving a log file but no error is generated. It is saved empty.

Can you try to simulate this situation and see what happens for yourself? Make a bands stack, load it into bandset1, set the wavelenght, generate any roi and view the spectral plot?

Here's a screenshot of how the stack I load is configured.

![stack](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/104084558/ce7e7b4b-0288-4202-9c72-b25ab7b7c555)

**Comment by semiautomaticgit** [comment] 2023-11-11 11:00
Hello @claudioasn ,

thank you for reporting this.

> Could the problem be in the construction of the stack and/or when it is loaded into the bandset? I've tried saving a log file but no error is generated. It is saved empty.

It is quite strange that the log file is empty, there could be some installation issues.

> Can you try to simulate this situation and see what happens for yourself? Make a bands stack, load it into bandset1, set the wavelenght, generate any roi and view the spectral plot?

The issue is related to Remotior Sensus library, and the way it manages multiband raster. For the moment, I recommend using single band rasters when creating band sets.

> So out of curiosity I tried to generate the PCA with the L8 level 1 bands (before the DOS correction), and apparently it worked correctly, as shown in the image below. So the question remains as to which step the problem is occurring: if already in the DOS generation or if in the generation of the Stack. I have another topic open that says that when I try to make the DOS correction and load the metadata file, SCP gives an error (shown in the other topic). Could this be the start of what's causing all these problems?

I'll try to check if there are issues in the DOS process.
However, if you are using Landsat collection 2 I recommend using level 2 images which are already atmospherically corrected with a method that is more accurate than DOS.

**Comment by claudioasn** [comment] 2023-11-12 02:42
Hello, @semiautomaticgit, I've tried again in various ways. Making a bandset only with the separate bands after performing DOS, making a stack bands... in short, there is always some problem, and I have tested it on more than one computer. Both problems with the spectral plot after dos and stack bands, as well as generating pca

As for the level 2 collection, I'm going to try using it, but as I teach remote sensing I like to show the procedure for correcting level 1 data or data analogous to it as well.

I checked here that my python version in qgis is 3.9, and not 3.10 (recommended by remotior-sensus). Could this be causing these problems? How can I upgrade it via the osgeo4w shell?

**Comment by semiautomaticgit** [comment] 2023-11-12 10:59
> Hello, @semiautomaticgit, I've tried again in various ways. Making a bandset only with the separate bands after performing DOS, making a stack bands... in short, there is always some problem, and I have tested it on more than one computer. Both problems with the spectral plot after dos and stack bands, as well as generating pca

Hello @claudioasn , thank you for the feedback, I'll look into it.

> As for the level 2 collection, I'm going to try using it, but as I teach remote sensing I like to show the procedure for correcting level 1 data or data analogous to it as well.

I understand.

> I checked here that my python version in qgis is 3.9, and not 3.10 (recommended by remotior-sensus). Could this be causing these problems? How can I upgrade it via the osgeo4w shell?

It could be related to Python version, but unfortunately I don't know how to upgrade it via osgeo4w.

**Comment by semiautomaticgit** [comment] 2023-11-23 14:00
Hi @claudioasn , it should be fixed now. Please update both SCP and Remotior Sensus.
Thank you for your feedback.

**Closed by semiautomaticgit** 2023-11-23 14:00 UTC

**Comment by claudioasn** [comment] 2023-11-23 23:20
Hi @semiautomaticgit 

I confirm that now the spectral plot is working with de band stack, even with the DOS files. However, the PCA still has problems with the DOS bands. I works with the original L1 or L2 bands, without image conversion. I tested with bandsets composed by separated bands and a bandstack.
