### ISSUE TITLE
SCP: failed download 

### ISSUE THREAD

**Issue by Humkoop** [semiautomaticgit/SemiAutomaticClassificationPlugin#316] opened 2023-11-14 14:35 UTC
[SCP Version 8.1.3.pdf](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/13349945/SCP.Version.8.1.3.pdf)

Good day all,

I've tried to download Sentinel 2A, but when it shows in the window, I'm unable to download the bands to a folder
e.g SCP: failed download L2A_T35HKC_A043790_20231110_B08

Please i need some help

Kind regards
Riaan

**Comment by semiautomaticgit** [comment] 2023-11-14 20:16
Hello @Humkoop , 
I was able to download these images so it must be something related to your system or network. Are you using a proxy?

Also, you can export the download links and try to download the bands in a browser https://semiautomaticclassificationmanual.readthedocs.io/en/latest/download_products_tab.html#download

**Comment by Humkoop** [comment] 2023-11-15 05:54
Good day Luca,

I’ve tried it with the proxy and without the proxy. Attached is the download link, whenever the image load I can click on Run and select a folder, after that nothing happens

Regards
Riaan

**Comment by semiautomaticgit** [comment] 2023-11-15 19:40
Hello @Humkoop , unfortunately I can't reproduced the issue.
I'll try look into it.

**Comment by semiautomaticgit** [comment] 2024-08-03 09:14
Hello @Humkoop ,

I'm closing this as it should be solved in the latest version of SCP.
Of course, please reopen it if it is still relevant.

**Closed by semiautomaticgit** 2024-08-03 09:14 UTC
