### ISSUE TITLE
scp plug-in faild when search sentinel 2 images

### ISSUE THREAD

**Issue by artterrm** [semiautomaticgit/SemiAutomaticClassificationPlugin#314] opened 2023-11-09 15:33 UTC
Hello. I try download sentinel 2 images via scp plug-in.  But I can't search images area of interest. Got error 'Search failed ,
Why?

**Comment by semiautomaticgit** [comment] 2023-11-09 20:41
Hello @artterrm , please update both SCP and Remotior Sensus. 
If you still get the same issue, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by artterrm** [comment] 2023-11-21 01:45
ERROR|2023-11-21T11:42:40.399|multiprocess_manager|multi_download_file|2348|Error proc 0-cannot unpack non-iterable NoneType object
ERROR|2023-11-21T11:42:40.399|download_products|query_sentinel_2_database|357|error: search failed

**Comment by artterrm** [comment] 2023-11-21 10:20
still cant search
but somtimes can do it

**Comment by semiautomaticgit** [comment] 2023-11-21 17:53
@artterrm thank you for the log file. 
The fact that sometimes the download works could indicate an issue of the service or the network.
I'll try to look into it.

**Comment by artterrm** [comment] 2023-11-22 04:25
Video 
How I try to search
https://disk.yandex.ru/i/23TxsoQOhGfvVw

**Comment by artterrm** [comment] 2023-11-22 04:28
The video shows that there are found pictures from the last successful time

**Comment by semiautomaticgit** [comment] 2023-11-23 14:23
Hello @artterrm , please update both SCP and Remotior Sensus.
When searching, please note that Login is only required for HLS products, not Copernicus Sentinel-2.
About the error, you can try to search defining a larger area.

**Comment by artterrm** [comment] 2023-11-24 09:27
Hello.
If login is only required for HLS products,  not Sentinel 2 what does required for sentinel 2?

**Comment by semiautomaticgit** [comment] 2023-11-24 20:56
> Hello. If login is only required for HLS products, not Sentinel 2 what does required for sentinel 2?

The service doesn't require any authentication.

> https://gis.stackexchange.com/questions/469878/scp-plug-in-failed-when-search-sentinel-2-images/470786#470786
> 
> I also asked on this resource. Here is the answer
> 
> I try it method but it not work

I can't reproduce the issue, so I think it is something related to the system or the network.
Unfortunately I don't have a solution.

Please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by artterrm** [comment] 2023-12-17 01:14
search() got an unexpected keyword argument 'copernicus_user

hello. new error

**Comment by semiautomaticgit** [comment] 2023-12-20 20:36
@artterrm please update both SCP and Remotior Sensus.

**Comment by semiautomaticgit** [comment] 2024-01-05 09:04
I'm closing this because it should be fixed with the latest updates. Of course, please reopen it if the error occurs again.

**Closed by semiautomaticgit** 2024-01-05 09:04 UTC

**Comment by artterrm** [comment] 2024-01-05 09:10
Hello.
Ok

пт, 5 янв. 2024 г., 19:04 Luca Congedo ***@***.***>:
