### ISSUE TITLE
Semi-automatic Classification Plugin crashed QGIS

### ISSUE THREAD

**Issue by hehesecret** [semiautomaticgit/SemiAutomaticClassificationPlugin#291] opened 2023-10-09 02:40 UTC
I ran into some problem where my SCP wont show on top together with other tools. I tried uninstalling the plugin, updating my QGIS, and freeing up my memory but the result still crashes my QGIS.
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/147358976/1b536497-f266-4915-8f3a-4736b0332969)

**Comment by semiautomaticgit** [comment] 2023-10-09 17:44
Hello, please try to update the plugin, then restart QGIS

**Comment by abubakars** [comment] 2023-10-10 14:01
Same here, even after I restart QGIS, it's still not available

**Comment by SUPHOT777** [comment] 2023-10-10 17:31
After I'd restart my Qgis then I got this window feature to show me that I couldn't use SCP Plugin. 
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/147542614/849e64df-4084-402c-a64c-a4b528e111ee)

**Comment by SUPHOT777** [comment] 2023-10-11 02:02
@semiautomaticgit I was installed 8.0.3 sir.
![image](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/147542614/61598600-6b42-4bfd-8b78-0ced66cf5e2d)

**Comment by resfiando** [comment] 2023-10-11 08:44
I have the same problem also.
1. Uninstall the Semi Automatic Plug In --> close QGIS.
2. Open QGIS -> Manage & Install Plugins --> Uninstall the Semi Automatic Plug In (again, don't know previous uninstallation is not working) --> close QGIS.
3. Open QGIS --> Manage & Install Plugins --> Install the Semi Automatic Plug In (then it's work).

May be there are bugs in installation process.
You can try my step

**Comment by semiautomaticgit** [comment] 2023-10-11 16:35
@abubakars @SUPHOT777 you can try what @resfiando suggested

> 1. Uninstall the Semi Automatic Plug In --> close QGIS.
> 2. Open QGIS -> Manage & Install Plugins --> Uninstall the Semi Automatic Plug In (again, don't know previous uninstallation is not working) --> close QGIS.
> 3. Open QGIS --> Manage & Install Plugins --> Install the Semi Automatic Plug In (then it's work).

**Comment by abubakars** [comment] 2023-10-11 19:47
I installed version 8.0.3, but still no luck; I had to downgrade to 7.10.

**Comment by TysonDude** [comment] 2023-10-12 11:32
I have the same issue. I reported the issue here.

**Comment by semiautomaticgit** [comment] 2023-10-12 20:12
I think it is something related to the combination of QGIS version and operating system, because I can't reproduce the issue.
I'll try to look into it.
In the meantime you can try the installation with Conda
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation_conda.html

**Comment by semiautomaticgit** [comment] 2023-10-12 20:18
An installation from scratch seems to solve the issue https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/294

**Comment by TysonDude** [comment] 2023-10-13 04:49
To the author - I suggest to install the older version 7. It worked for me. (Owner's suggestion as well)
To the owner - Installing python library files from Conda or Miniforge is too hard & confusing for those who don't know coding & using QGIS just for some basic GIS works (just like me). So please resolve the new plugin issue. Make it proper without any extra downloads from outside, so we can use it. 
Also, Thanks for the amazing feature. It helped us a lot.

**Comment by semiautomaticgit** [comment] 2023-10-13 18:40
> To the author @hehesecret - I suggest to install the older version 7. It worked for me. (Owner's suggestion as well) To the owner @semiautomaticgit - Installing python library files from Conda or Miniforge is too hard & confusing for those who don't know coding & using QGIS just for some basic GIS works (just like me). So please resolve the new plugin issue. Make it proper without any extra downloads from outside, so we can use it. Also, Thanks for the amazing feature. It helped us a lot.

You are welcome. I'll try to make the installation simpler.

**Comment by semiautomaticgit** [comment] 2023-10-18 22:07
I'm closing this because the installation issues should be solved. Of course please reopen it in case it is still present.

**Closed by semiautomaticgit** 2023-10-18 22:07 UTC
