### ISSUE TITLE
Problems in accuracy evaluation

### ISSUE THREAD

**Issue by zhulei1024** [semiautomaticgit/SemiAutomaticClassificationPlugin#178] opened 2021-05-30 17:28 UTC
I have chosen the classification to access and the reference raster, but it always shows an error that: ERROR 9: none raster found, how should I deal with it? Thank you very much.

**Comment by semiautomaticgit** [comment] 2021-05-30 18:57
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by zhulei1024** [comment] 2021-05-31 06:27
> Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

[log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6568185/log.txt)
Here is the log file, thanks in advance!

**Comment by semiautomaticgit** [comment] 2021-05-31 19:40
Thank you for the log file. 
I think the issue is related to the input file path. You could try to move all the input file in a directory without special characters (e.g. C:\input)

**Comment by zhulei1024** [comment] 2021-06-05 16:33
> Thank you for the log file.
> I think the issue is related to the input file path. You could try to move all the input file in a directory without special characters (e.g. C:\input)

[bug.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/6602867/bug.txt)
I have changed the directory but still the error occurs TT

**Comment by semiautomaticgit** [comment] 2021-06-07 16:25
Thank you for the log file.
I suspect it is an installation issue.
Could you please try this sample dataset https://docs.google.com/uc?id=1cph9rCQ1oiWgRGusgRkjUWwLW3JEwqUK

**Comment by semiautomaticgit** [comment] 2022-09-07 21:47
I'm closing this, but in case you still have this issue please reopen this

**Closed by semiautomaticgit** 2022-09-07 21:47 UTC
