### ISSUE TITLE
Error SCP 7.5.6 Sentinel-2 download.

### ISSUE THREAD

**Issue by Jules428** [semiautomaticgit/SemiAutomaticClassificationPlugin#153] opened 2021-02-05 12:25 UTC
Error [56] SSL Connection error when downloading Sentinel-2 images 
Mac OS 11.2

**Comment by semiautomaticgit** [comment] 2021-02-07 09:37
Hello, I think it is a duplicate of https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/135
Please try the suggested solutiob

**Closed by semiautomaticgit** 2021-02-07 09:37 UTC
Labels: Mac
