### ISSUE TITLE
Random Forest does not start

### ISSUE THREAD

**Issue by gkakogeorgiou** [semiautomaticgit/SemiAutomaticClassificationPlugin#154] opened 2021-02-07 09:21 UTC
Hello,
I tried to run random forest classifier; however, when I push the Run button, no window prompts to select the .tif output file and the following warning appears. 
![Warning-rf](https://user-images.githubusercontent.com/67234311/107142294-7f4f8380-6936-11eb-9f14-54c94bb08d86.PNG)

Note that for other classification options, everything works ok. Also, when I try Test dependencies, everything "succeeds"; however, an error appears on the log file.

![Test-Results](https://user-images.githubusercontent.com/67234311/107142293-7eb6ed00-6936-11eb-8e9a-c6186204cc0e.PNG)

![logfile](https://user-images.githubusercontent.com/67234311/107142292-7ced2980-6936-11eb-81e8-70b293c2f741.PNG)

I use updated versions for qgis, scp and snap.

**Comment by semiautomaticgit** [comment] 2021-02-07 09:40
Hello, it seems that the band set is empty.
Could you please repeat the whole process starting from band set creation and attach the log file as text?

**Comment by gkakogeorgiou** [comment] 2021-02-07 09:51
2021-02-07 11.49.28.910759	SemiAutomaticClassificationPlugin.core.utils-clearLogFile 504	LOG ACTIVE SemiAutomaticClass Version 7.5.6 - Matera - QGIS v. 31603 L:en - OS Windows - 64bit =Yes
2021-02-07 11.49.56.419269	SemiAutomaticClassificationPlugin.core.input-refreshRasterLayer 72	raster layers refreshed
2021-02-07 11.49.56.420269	SemiAutomaticClassificationPlugin.maininterface.bandsetTab-clearBandSet 493	 band set cleared
2021-02-07 11.49.56.423270	SemiAutomaticClassificationPlugin.maininterface.bandcalcTab-outputNameTable 260	 output name table created
2021-02-07 11.49.56.424268	SemiAutomaticClassificationPlugin.maininterface.bandcalcTab-rasterBandName 404	 raster band name checklist created
2021-02-07 11.49.56.425271	SemiAutomaticClassificationPlugin.maininterface.bandsetTab-readBandSet 805	 read band set
2021-02-07 11.49.56.439270	SemiAutomaticClassificationPlugin.maininterface.bandsetTab-configureBandSet 817	 configure band set
2021-02-07 11.49.56.440270	SemiAutomaticClassificationPlugin.core.utils-selectLayerbyName 6596	layer selected: s2_18_9_20_pdc_1_rayl#b0
2021-02-07 11.49.56.441271	SemiAutomaticClassificationPlugin.core.utils-checkBandSet 2101	 raster is not loaded: s2_18_9_20_pdc_1_rayl#b0
2021-02-07 11.49.56.443270	SemiAutomaticClassificationPlugin.maininterface.algorithmWeightTab-resetAlgorithmTable 47	 reset Algorithm Table
2021-02-07 11.49.56.444269	SemiAutomaticClassificationPlugin.maininterface.algorithmWeightTab-readAlgorithmTable 93	
2021-02-07 11.49.56.445269	SemiAutomaticClassificationPlugin.maininterface.bandsetTab-rasterLayerName 464	input raster: s2_18_9_20_pdc_1_rayl
2021-02-07 11.50.06.066655	SemiAutomaticClassificationPlugin.core.utils-removeLayer 6383	layer: training_input
2021-02-07 11.50.06.098653	SemiAutomaticClassificationPlugin.dock.scpdock-getROIAttributes 1212	 ROI attributes
2021-02-07 11.50.06.109655	SemiAutomaticClassificationPlugin.maininterface.LCSignatureThresholdTab-checkIntersections 172	
2021-02-07 11.50.06.110656	SemiAutomaticClassificationPlugin.maininterface.LCSignatureThresholdTab-higlightRowsByID 220	
2021-02-07 11.50.06.112656	SemiAutomaticClassificationPlugin.maininterface.LCSignatureThresholdTab-LCSignatureThresholdListTable 142	 signature list threshold created
2021-02-07 11.50.06.113656	SemiAutomaticClassificationPlugin.maininterface.signatureThresholdTab-signatureThresholdListTable 66	 signature list threshold created
2021-02-07 11.50.06.115656	SemiAutomaticClassificationPlugin.core.utils-fieldID 8003	ID: 3 for layer: training_input
2021-02-07 11.50.06.116655	SemiAutomaticClassificationPlugin.dock.scpdock-openSignatureListFile 612	 opened signature 3
2021-02-07 11.50.06.117655	SemiAutomaticClassificationPlugin.dock.scpdock-openSignatureList 251	 signatures opened: C:/Users/gkako/AppData/Local/Temp/semiautomaticclassification/20210207_114918762495/training_input20210207_115006054644/training_input.slf
2021-02-07 11.50.06.129654	SemiAutomaticClassificationPlugin.dock.scpdock-openInput 276	 signatures opened: D:/debris-detection/semi-automatic-test/training_input.scp
2021-02-07 11.50.25.586204	SemiAutomaticClassificationPlugin.maininterface.randomForestTab-performRandomForest 173	Perform random forest classification

**Comment by semiautomaticgit** [comment] 2021-02-07 10:12
Thank you, it seems that raster s2_18_9_20_pdc_1_rayl is not loaded in QGIS.
Could you please share also a screenshot of the Band set tab?

**Comment by gkakogeorgiou** [comment] 2021-02-07 10:15
![band_set](https://user-images.githubusercontent.com/67234311/107143519-33084180-693e-11eb-80fa-e63408a8328d.PNG)
![qgis](https://user-images.githubusercontent.com/67234311/107143522-34d20500-693e-11eb-8313-69767825eaa9.PNG)

The raster is already stacked.

**Comment by semiautomaticgit** [comment] 2021-02-07 10:19
I'm going to check if the issue is related to stacker layer.
In the meantime I suggest to try create a Band set using the single band rasters (you can split bands using this https://semiautomaticclassificationmanual.readthedocs.io/en/latest/splitrasterbandsTab.html)

**Comment by gkakogeorgiou** [comment] 2021-02-07 10:38
Thank you very much, it seems that it works now. The issue was related to the stacked layer.

**Comment by semiautomaticgit** [comment] 2021-02-07 18:39
You are very welcome.
It should be fixed in version 7.5.7. 
Please reopen this if you still have this issue

**Closed by semiautomaticgit** 2021-02-07 18:39 UTC
