### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by bakkerss** [semiautomaticgit/SemiAutomaticClassificationPlugin#347] opened 2024-03-26 20:38 UTC
During the execution of this plugin a collegue gets the error berlow. I hope the error message provides sufficient information to find the problem. If not please let me know and I will ask for the exact steps to replicate the issue step by step.

UnboundLocalError: local variable 'output' referenced before assignment 
Traceback (most recent call last):
  File "C:\Users/teunv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 143, in run_classification_action
    run_classifier()
  File "C:\Users/teunv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\classification_tab.py", line 487, in run_classifier
    if output is None:
UnboundLocalError: local variable 'output' referenced before assignment

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.28.4-Firenze Firenze, fd0fb72ab3 
Python pad:
•	C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python
•	C:/Users/teunv/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/teunv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins
•	C:\Program Files\QGIS 3.28.4\bin\python39.zip
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib
•	C:\Program Files\QGIS 3.28.4\bin
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/teunv/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/teunv/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin
•	C:/Users/teunv/Documents/school/stage/binnenlandstage/QGIS

**Comment by semiautomaticgit** [comment] 2024-03-27 21:03
Hello, this is a duplicate of https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/330 .
Probably it is related to input data.

Please enable "Records detailed events in a log file" and copy the log file as described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error and copy the log file [here](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/330).

**Closed by semiautomaticgit** 2024-03-27 21:03 UTC
