### ISSUE TITLE
Issues Preprocessing more than one image at the same time and problems with create virtual raster of band set

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#130] opened 2020-11-10 12:42 UTC
Hi Luca,

I'm downloading two Sentinel-2 L1C images from different dates, and I would like to apply DOS1 atmospheric correction, calculate NDVI, EVI and NBR vegetation indices, at the same time for both dates, and also create a virtual raster bandset for each one. 

The options I'm choosing are:

![SCP_1_Download](https://user-images.githubusercontent.com/1331581/98674567-e74ef780-2350-11eb-9c1b-1aee367ae314.jpg)

![SCP_2_Preprocess](https://user-images.githubusercontent.com/1331581/98674587-ed44d880-2350-11eb-9abc-8380c7a70af1.jpg)

![SCP_3_Bandset](https://user-images.githubusercontent.com/1331581/98674599-f2a22300-2350-11eb-90ca-c6af80f20a23.jpg)

![SCP_4_BandCalc](https://user-images.githubusercontent.com/1331581/98674615-f8980400-2350-11eb-89a1-7827dcbe6a41.jpg)

Both set of images are correctly downloaded, but the preprocessing and band calc of vegetation indices are only applied to one date.

Virtual raster bandsets are not created at all, but that seems to be a different issue, because if I select in the Band set tab -> Band set tools -> "Create virtual raster of band set" **AND** "Band calc expressions", SCP only executes the Band calc expression, and does not create the virtual raster (or the stack), even with only one image. If I do not choose the band calc expressions option, the virtual band ser is created.

Do you confirm these issues, or am I missing something Luca?

**Comment by semiautomaticgit** [comment] 2020-11-11 19:17
Hi Pedro,
thank you for reporting this. I'll look into this

**Comment by semiautomaticgit** [comment] 2020-11-13 00:03
Hi Pedro,

it should be fixed in version 7.0.12. 
Please reopen this if you still have issues.

**Closed by semiautomaticgit** 2020-11-13 00:03 UTC

**Comment by PedroVenancio** [comment] 2020-11-13 10:59
Hi @semiautomaticgit 

Thank you very much!

I've installed 7.0.12 and I see two issues:

- The bounding box of the search area is not shown on canvas:

![imagem](https://user-images.githubusercontent.com/1331581/99063873-135eb880-259d-11eb-8f25-b0303559d393.png)

- Now the preprocessing is not applied to any of the downloaded images, despite both dates are correctly downloaded. 

![imagem](https://user-images.githubusercontent.com/1331581/99065383-38542b00-259f-11eb-97fb-24ee33a2bb8f.png)

![imagem](https://user-images.githubusercontent.com/1331581/99065431-499d3780-259f-11eb-9847-cce8ea9eb379.png)


Here is the log file:

[SCP_7_0_12_LOG.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/5536282/SCP_7_0_12_LOG.txt)

Thanks Luca!

**Comment by PedroVenancio** [comment] 2020-11-13 11:57
Luca, sorry, I can't replicate the first issue now. So it seems everything ok with BBox. Sorry for the noise.

**Comment by semiautomaticgit** [comment] 2020-11-14 14:40
Hi Pedro, no problem, thank you for reporting this

**Comment by PedroVenancio** [comment] 2020-11-17 19:23
Hi @semiautomaticgit 

Now I see that this issue https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/130#issuecomment-726699927 is true in QGIS 3.16, also with SCP 7.0.15.

I was using two profiles between QGIS 3.10.11 and 3.16.0, and I made a confusion, but now I see that this is true in 3.16.0.

Can you take a look Luca?

Thanks!

**Comment by semiautomaticgit** [comment] 2020-11-21 18:51
> Hi @semiautomaticgit
> 
> Now I see that this issue [#130 (comment)](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/130#issuecomment-726699927) is true in QGIS 3.16, also with SCP 7.0.15.
> 
> I was using two profiles between QGIS 3.10.11 and 3.16.0, and I made a confusion, but now I see that this is true in 3.16.0.
> 
> Can you take a look Luca?
> 
> Thanks!

Hi Pedro, I can't reproduce the issue. 
Please try disabling any other plugin and try again.
Thank you

**Comment by PedroVenancio** [comment] 2020-11-21 20:29
Hi @semiautomaticgit 

It seems to be something with newer GDAL/OGR or PROJ versions.

**SCP works fine in:**

Versão do QGIS | 3.10.11-A Coruña | Revisão do código do QGIS | d2171173e4
-- | -- | -- | --
Compilado com Qt | 5.11.2 | Em execução com Qt | 5.11.2
Compilado com GDAL/OGR | 3.1.4 | Em execução com GDAL/OGR | 3.1.4
Compilado com GEOS | 3.8.1-CAPI-1.13.3 | Em execução com GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versão de cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 6.3.2 | Em execução com PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)



Versão do QGIS | 3.16.0-Hannover | Revisão do código do QGIS | 43b64b13f3
-- | -- | -- | --
Compilado com Qt | 5.11.2 | Em execução com Qt | 5.11.2
Compilado com GDAL/OGR | 3.1.4 | Em execução com GDAL/OGR | 3.1.4
Compilado com GEOS | 3.8.1-CAPI-1.13.3 | Em execução com GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versão de cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 6.3.2 | Em execução com PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)


**But does not work in (from OSGeo4W):**

Versão do QGIS | 3.16.0-Hannover | Revisão do código do QGIS | 0284dcf30f
-- | -- | -- | --
Compilado com Qt | 5.11.2 | Em execução com Qt | 5.11.2
Compilado com GDAL/OGR | 3.3.0dev | Em execução com GDAL/OGR | 3.3.0dev
Compilado com GEOS | 3.8.1-CAPI-1.13.3 | Em execução com GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
Versão de cliente PostgreSQL | 11.5 | Versão SpatiaLite | 4.3.0
Versão QWT | 6.1.3 | Versão QScintilla2 | 2.10.8
Compilado com PROJ | 8.0.0 | Em execução com PROJ | Rel. 8.0.0, March 1st, 2021
OS Version | Windows 10 (10.0)
